language: scala
jdk: oraclejdk8
scala: 2.11.8
script: sbt ++$TRAVIS_SCALA_VERSION --warn test dist

before_deploy:
- PROJECT_NAME=`grep ^name build.sbt  | sed s"/name.*:=.*\"\(.*\)\"/\1/"`
- VERSION=`grep ^version build.sbt  | sed s"/version.*:=.*\"\(.*\)\"/\1/"`
- FILE=target/universal/$PROJECT_NAME-$VERSION.zip
- echo "VARAIBLES:"
- echo $PROJECT_NAME
- echo $VERSION
- echo $FILE
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- git remote add origin-test https://${GITHUB_TOKEN}@github.com/DEIB-GECO/GMQL-WEB.git
- git push --delete origin-test $VERSION || true
- echo $TRAVIS_TAG
- if [ -z "$TRAVIS_TAG" ]; then TRAVIS_TAG=$VERSION; fi
- echo $TRAVIS_TAG
- ls target/universal/

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "$FILE"
  on:
    repo: DEIB-GECO/GMQL-WEB
    all_branches: true
    condition: $TRAVIS_BRANCH == "master"
  skip_cleanup: true
  overwrite: true
env:
  global:
  - secure: e3mp4C4/Hl3TWY/WqNrqgBs9RaFUckmkzTT4NRpZEncwzrcDfCj6pTUDQ37Sbrw/Fnue+gc8BVE30SLxlQhzkQDTy6xm74BXUUH2arp57BfTycPnfjw85h3+eFlv6+Q0NfxB0vcn4YIdgrJ20h5zksl00Te7yeS5nGQBU6/kttjXMZWvELJAi8oXgxMNXxvFrxaBErePeoNVP5dpGPZxgVxWUQMPRD3gYnWX0Rvf5gcwlRgM73ugELrefKGag8//WEMAWhLcpYT2tjy6poKvQ5OaqdOUrtJzBjyrsWR5VU//KG5FsVRq4TdzT4Nkv/3yvxHLSm2Qfd2Oh8BrmBei3juP/CAtkA6+cUaI3SBejjizKv2Swi2rrEpIILRgBg0JDIZSbCyG6fO0HcnwXImCk3h1J7h/M4IKwhDHd0eJ8lM9hNxo0vL5+3Z4WU1jHbzwgkH7rP1hDSTGfqPCB1hKIRaFG8U1rmAfLVzLAWr0CvrlQODp/EOz7CibXyTuWR5eYQORCqDl4g09YYnA1Js19Y0H7zyeA/TXkxUVsChqDjQz/VW53+PiYFAm6gkKR8xOxh7+y29xh4o0ab4YboHIadC9RcDwYkMzsXp2x3CEsOqB8Z/utPYI8JiT/tRsG3F76IYHsDrrMGimiiEqcM3U4fxaI3y3Hgj8YbFNNireNus=
  - secure: h8DoCQCbBuRr8DplDbxCUte49OzAvDSVexgviUen1vv0w7mbtgDu0WYp6LtUaZAlwLbrd1zYnlkf4Vb8MjkF9vyvkqEOeW5fn08n6CALYN+7aIn5bpZEsmn+tyjlEZGxWCubqb/9QWA9KTsI4QW+Yu1Az8/0oxzn3FQgc8lOwoeJtA72ztKCeo5rbBSDjMEgL9zeAWQTgSlsCclCEnAkiwUnvTuoqM5wsnyLXA3uUhvmIqY8/ICgjRDsyj7iILWcsmowxrkLehdAoMwvBkLsSsEkzpT02xkZqnseVAENpzQPxeR/QUZRjMrGaHZbA4agpncq5YxXC2jgwrICkAsdzrNP8vfrKAhyPDycb9PAs2zopdS4O7KPu9Og/qxVkx3rdmt2sLb03NgT3UmT2y+3vqFfvjrTLaTZSeCM1W3XVgGFCHk1STiU2hHtEINAzcJKSbiSERR3p4c5jTIlOJC71X3jfrhxQhfUU2qMvNCt4p3LPxbVbZazsQ1IxolCOPFMrfmLrhK2hTe1r35QbwIGIdUHaglFf53pTGGjOp1bEJTMynWeg/wx5Z6Yl3Yia8cN+qI3wXhPOSX5ONfKVV4TBK1ktlNhAEBuanmrtLvgla8eQ8D5dYAjMcr8+/5k3LdcVK+tUACXBqHZXo5hvlQFLFYZUhYuyGC7q9VaWct7R3w=
